# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\mycode\GoodsBook\ui\shipping_record.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1035, 419)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBoxOutputRecordBuyer = ExtendedComboBox(self.widget_3)
        self.comboBoxOutputRecordBuyer.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBoxOutputRecordBuyer.setObjectName("comboBoxOutputRecordBuyer")
        self.gridLayout_6.addWidget(self.comboBoxOutputRecordBuyer, 1, 6, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 0, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 0, 2, 1, 1)
        self.comboBoxOutputRecordGoods = ExtendedComboBox(self.widget_3)
        self.comboBoxOutputRecordGoods.setMinimumSize(QtCore.QSize(200, 30))
        self.comboBoxOutputRecordGoods.setObjectName("comboBoxOutputRecordGoods")
        self.gridLayout_6.addWidget(self.comboBoxOutputRecordGoods, 1, 5, 1, 1)
        self.pushButtonQueryOutputRecord = QtWidgets.QPushButton(self.widget_3)
        self.pushButtonQueryOutputRecord.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonQueryOutputRecord.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonQueryOutputRecord.setFont(font)
        self.pushButtonQueryOutputRecord.setObjectName("pushButtonQueryOutputRecord")
        self.gridLayout_6.addWidget(self.pushButtonQueryOutputRecord, 1, 7, 1, 1)
        self.dateEditBeginOutputRecord = CCustomDateEdit(self.widget_3)
        self.dateEditBeginOutputRecord.setMinimumSize(QtCore.QSize(0, 30))
        self.dateEditBeginOutputRecord.setMaximumSize(QtCore.QSize(123, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEditBeginOutputRecord.setFont(font)
        self.dateEditBeginOutputRecord.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEditBeginOutputRecord.setObjectName("dateEditBeginOutputRecord")
        self.gridLayout_6.addWidget(self.dateEditBeginOutputRecord, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 0, 6, 1, 1)
        self.dateEditEndOutputRecord = CCustomDateEdit(self.widget_3)
        self.dateEditEndOutputRecord.setMinimumSize(QtCore.QSize(0, 30))
        self.dateEditEndOutputRecord.setMaximumSize(QtCore.QSize(123, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEditEndOutputRecord.setFont(font)
        self.dateEditEndOutputRecord.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEditEndOutputRecord.setObjectName("dateEditEndOutputRecord")
        self.gridLayout_6.addWidget(self.dateEditEndOutputRecord, 1, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 0, 1, 1)
        self.labelAmount = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAmount.setFont(font)
        self.labelAmount.setStyleSheet("color:rgb(0, 0, 255)")
        self.labelAmount.setObjectName("labelAmount")
        self.gridLayout_6.addWidget(self.labelAmount, 1, 8, 1, 1)
        self.labelProfile = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelProfile.setFont(font)
        self.labelProfile.setStyleSheet("color:rgb(255, 0, 0)")
        self.labelProfile.setObjectName("labelProfile")
        self.gridLayout_6.addWidget(self.labelProfile, 1, 9, 1, 1)
        self.labelNum = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNum.setFont(font)
        self.labelNum.setStyleSheet("color:rgb(0, 0, 255)")
        self.labelNum.setObjectName("labelNum")
        self.gridLayout_6.addWidget(self.labelNum, 0, 8, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.tableWidgetOutputRecord = QtWidgets.QTableWidget(Form)
        self.tableWidgetOutputRecord.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidgetOutputRecord.setRowCount(0)
        self.tableWidgetOutputRecord.setColumnCount(0)
        self.tableWidgetOutputRecord.setObjectName("tableWidgetOutputRecord")
        self.tableWidgetOutputRecord.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidgetOutputRecord)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_24.setText(_translate("Form", "商品"))
        self.label_23.setText(_translate("Form", "结束日期"))
        self.pushButtonQueryOutputRecord.setText(_translate("Form", "查询"))
        self.label_26.setText(_translate("Form", "买家"))
        self.label_22.setText(_translate("Form", "开始日期"))
        self.labelAmount.setText(_translate("Form", "总售货金额:"))
        self.labelProfile.setText(_translate("Form", "总利润:"))
        self.labelNum.setText(_translate("Form", "总售货数量:"))
        self.tableWidgetOutputRecord.setSortingEnabled(True)

from lib.pubui import CCustomDateEdit, ExtendedComboBox
