# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\mycode\GoodsBook\ui\shipping.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1006, 479)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(30, 20, 30, 20)
        self.gridLayout_2.setSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.comboBoxOutputBuyer = ExtendedComboBox(Form)
        self.comboBoxOutputBuyer.setMinimumSize(QtCore.QSize(0, 50))
        self.comboBoxOutputBuyer.setObjectName("comboBoxOutputBuyer")
        self.gridLayout_2.addWidget(self.comboBoxOutputBuyer, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.comboBoxOutputGoods = ExtendedComboBox(Form)
        self.comboBoxOutputGoods.setMinimumSize(QtCore.QSize(0, 50))
        self.comboBoxOutputGoods.setObjectName("comboBoxOutputGoods")
        self.gridLayout_2.addWidget(self.comboBoxOutputGoods, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 5, 1, 1)
        self.lineEditOutputRemark = QtWidgets.QLineEdit(Form)
        self.lineEditOutputRemark.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditOutputRemark.setObjectName("lineEditOutputRemark")
        self.gridLayout_2.addWidget(self.lineEditOutputRemark, 2, 5, 1, 1)
        self.dateEditOutput = CCustomDateEdit(Form)
        self.dateEditOutput.setMinimumSize(QtCore.QSize(0, 50))
        self.dateEditOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEditOutput.setCalendarPopup(True)
        self.dateEditOutput.setObjectName("dateEditOutput")
        self.gridLayout_2.addWidget(self.dateEditOutput, 2, 0, 1, 1)
        self.pushButtonOutput = QtWidgets.QPushButton(Form)
        self.pushButtonOutput.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonOutput.setObjectName("pushButtonOutput")
        self.gridLayout_2.addWidget(self.pushButtonOutput, 3, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 4, 1, 1)
        self.lineEditOutputNum = QtWidgets.QLineEdit(Form)
        self.lineEditOutputNum.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditOutputNum.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOutputNum.setObjectName("lineEditOutputNum")
        self.gridLayout_2.addWidget(self.lineEditOutputNum, 2, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 3, 1, 1)
        self.lineEditOutputPrice = QtWidgets.QLineEdit(Form)
        self.lineEditOutputPrice.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditOutputPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOutputPrice.setObjectName("lineEditOutputPrice")
        self.gridLayout_2.addWidget(self.lineEditOutputPrice, 2, 3, 1, 1)
        self.labelAmount = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelAmount.setFont(font)
        self.labelAmount.setStyleSheet("color:rgb(0, 0, 255)")
        self.labelAmount.setObjectName("labelAmount")
        self.gridLayout_2.addWidget(self.labelAmount, 0, 4, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.gridLayout_2.setColumnStretch(2, 4)
        self.gridLayout_2.setColumnStretch(3, 2)
        self.gridLayout_2.setColumnStretch(4, 2)
        self.gridLayout_2.setColumnStretch(5, 6)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 2)
        self.gridLayout_2.setRowStretch(2, 3)
        self.gridLayout_2.setRowStretch(3, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "日期"))
        self.label_8.setText(_translate("Form", "买家"))
        self.label_7.setText(_translate("Form", "商品"))
        self.label_11.setText(_translate("Form", "备注"))
        self.pushButtonOutput.setText(_translate("Form", "确认出货"))
        self.label_9.setText(_translate("Form", "数量"))
        self.label_10.setText(_translate("Form", "价格"))
        self.labelAmount.setText(_translate("Form", "总价:"))

from lib.pubui import CCustomDateEdit, ExtendedComboBox
